services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      #- PUID=1000
      #- PGID=1000
      - TZ=Europe/Zurich
      - VERSION=docker
      #- PLEX_CLAIM= #optional
    volumes:
      - /dockerdata/plex/config:/config
      - /dockerdata/plex/tvseries:/tv
      - /dockerdata/plex/movies:/movies
    restart: unless-stopped