services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - "3000:3000"
    #env_file: .env
    volumes:
      - './config:/app/config'
      #- '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      HOMEPAGE_ALLOWED_HOSTS: gethomepage.dev
    #  PUID: $PUID
    #  PGID: $PGID
    restart: unless-stopped